### ISSUE TITLE
Is there any other way to define TsVector besides import_types?

### ISSUE THREAD

**Issue by oldner** [diesel-rs/diesel_full_text_search#42] opened 2024-05-29 13:25 UTC
Hi, I want to use `diesel_full_text_search::TsVector` only for a `table!`. But when I add it to `diesel.toml` in `import_types`, it adds to all `table!`s. I want to add it only for my `table!`. Because I have more than 150 tables. I don't want to update schema.rs manually either. So is there any other way to use `TsVector`?

**Comment by weiznich** [comment] 2024-05-29 14:54
Duplicate of https://github.com/diesel-rs/diesel/discussions/4052

**Closed as not planned by weiznich** 2024-05-29 14:54 UTC
